# # Use the latest 2.1 version of CircleCI pipeline process engine.
# # See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1

# # Define a job to be invoked later in a workflow.
# # See: https://circleci.com/docs/2.0/configuration-reference/#jobs
# jobs:
#   build:
#     # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
#     # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
#     docker:
#       - image: circleci/node
#     # Add steps to the job
#     # See: https://circleci.com/docs/2.0/configuration-reference/#steps
#     steps:
#       - checkout
#       - run: npm run test:ci

# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   build-workflow:
#     jobs:
#       - build
version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  bundle_dependencies:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install builder
          command : |
            yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules

  precompile:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Link Bundle Path
          command : |
            yarn build
      - save_cache:
          key: v1-assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo/dist

  deploy:
    machine: true

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v1-assets-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo ${CIRCLE_BRANCH}
      - run:
          name: Deploy build to GitHub Pages
          command: |
              set -e
              remote=$(git config remote.origin.url)
              if [ ! -d "build" ]
              then
                  echo "build folder not found"
                  exit 1
              fi
              mkdir gh-pages-branch
              cd gh-pages-branch
              git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
              git config --global user.name "$GH_NAME" > /dev/null 2>&1
              git init
              git remote add --fetch origin "$remote"
              if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
              then
                  git checkout gh-pages
                  git rm -rf .
              else
                  git checkout --orphan gh-pages
              fi
              cp -a "../build/." .
              git add -A
              git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
              git push --force --quiet origin gh-pages > /dev/null 2>&1
              cd ..
              rm -rf gh-pages-branch
              echo "Finished GitHub pages Deployment!"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code:
          filters:
            branches:
              ignore:
                - gh-pages
      - bundle_dependencies:
          requires:
            - checkout_code
      - precompile:
          requires:
            - bundle_dependencies
      - deploy:
          requires:
            - precompile
          filters:
            branches:
              only:
                - main
